feat: migrate docs
gemini-testing/testplane-docs pull request #6
Opened 2024-06-19 07:28 UTC by shadowusr

2024-06-19 11:24 UTC, KuznetsovRoman approved these changes
В остальном - /ok

2024-06-19 11:24 UTC, KuznetsovRoman commented on docs/quickstart/index.mdx
> +npm init testplane YOUR_PROJECT_PATH
Все таки, давай тут и на лендинге будем использовать `npm init testplane@latest`
Без приставки `@latest` может заюзаться старая имеющаяся версия `create-testplane` из кэша.
Поэтому этот суффикс `@latest`, по-моему, у всех в примерах стоит:

<img width="486" alt="image" src="https://github.com/gemini-testing/testplane-docs/assets/54893992/12eaebd3-28bc-457b-92d0-5d78249a05bf">


<img width="534" alt="image" src="https://github.com/gemini-testing/testplane-docs/assets/54893992/0ce593e6-8f61-45a2-bbfe-9b270b4bbde0">

2024-06-19 11:24 UTC, KuznetsovRoman commented on docs/quickstart/index.mdx
> +Чтобы пропустить бОльшую часть вопросов установщика, укажите опцию `-y`.
Неактуально. Теперь по умолчанию вопросы и так не задаются. Теперь чтобы эти вопросы задавались, нужно использовать `-v`: https://github.com/gemini-testing/create-testplane/blob/master/docs/ru/create-testplane.md#режим-продвинутой-установки

2024-06-19 11:24 UTC, KuznetsovRoman commented on docs/migrations/how-to-upgrade-hermione-to-4.mdx
Можем еще в раздел миграций добавить "миграция с hermione"? Или это в следующем(их) PR?

2024-06-19 11:24 UTC, KuznetsovRoman commented on docs/index.mdx
> +-   [ретраи инфраструктурных ошибок][retry-progressive].
`patterns-on-reject` - ведет на доку о соответствующей настройке (ожидаемое поведение)
`retry-progressive` - ведет на доку о соответствующем плагине
`retry-limiter` - ведет на гитхаб(!)

При том, что соответствующий плагин описан в документации: https://testplane-ci.website.yandexcloud.net/testplane-docs/website-static/9577940870-36-1/docs/v8/plugins/retry-limiter

Давай везде, где можем, юзать ссылки именно на доку

2024-06-19 11:24 UTC, KuznetsovRoman commented on docs/plugins/hermione-assert-view-extended.mdx
> +# hermione-assert-view-extended
Давай удалим эту страницу. Плагин не наш, и уже нерелевантный. Отключать анимацию `assertView` и сам умеет.

2024-06-19 11:24 UTC, KuznetsovRoman commented on docs/commands/expect/network-matchers.mdx
> +# expect для сети
У нас есть:
- `commands`
  - `browser`
  - `element`
  - `mock`
  - `expect`

При этом `expect` есть для `browser`, для `element`, и для "сети".
Давай, для консистентности, так же назовем и тут - `mock-matchers`, тем более, что в `expect` передается `mock`.

2024-06-19 12:34 UTC, miripiruni requested changes
Досмотрел до `docs/commands/browser/savePDF.mdx`. ПР очень большой, я поделю ревью на несколько заходов. Если не вернусь за сутки, то не жди, пожалуйста.

Нужно поправить пару важных замечаний (в посте про ребрендинг и про видео)

2024-06-19 12:34 UTC, miripiruni commented on blog/component-testing.mdx
> +Внутри браузера, в котором выполняется тест, доступны инстанс самого `browser` и инстанс `expect`. Это довольно удобно использовать при дебаге теста.
> Внутри браузера

nit: В консоли браузера, в котором …

2024-06-19 12:34 UTC, miripiruni commented on blog/rebranding.mdx
> +После рассмотрения всех за и против мы остановились на этом новом имени, которое, на наш взгляд, лучше всего подходит нашему продукту. Но не волнуйтесь, в самой сути ничего не изменилось. Testplane —
Довольно странный текст ничего не объясняющий о причинах ребрендинга, оставляющий непонимание что произошло и зачем.

Давай его перепишем как следует?

У нас есть аргументы:
1) мы хотим активнее вкладываться в разработку в опенсорсе, и новое название поможет подсветить, что наступил качественный переход в развитии инструмента
2) мы хотим сделать полноценный бренд с товарным знаком, логотипом, фирменным шрифтом и визуальным брендом. Чтобы сделать его уникальным и узнаваемым мы решили придумать новое название и историю про «испытательный полёт».

2024-06-19 12:34 UTC, miripiruni commented on docs/commands/browser/$.mdx
> +```javascript
html?

2024-06-19 12:34 UTC, miripiruni commented on docs/commands/browser/action.mdx
> +-   `down(value: string)` &mdash; создает действие нажатия клавиши;
здесь и всегда: вместо мнемоник следует использовать UTF-8 символы. А данном случае «–».

2024-06-19 12:34 UTC, miripiruni commented on docs/commands/browser/action.mdx
> +[appium-ios]: https://github.com/appium/appium-xcuitest-driver#mobile-pinch
Ссылка битая, правильная видимо тут https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-pinch

2024-06-20 15:35 UTC, sipayRT approved these changes

2024-06-23 17:57 UTC, shadowusr commented on docs/migrations/how-to-upgrade-hermione-to-4.mdx
Этот PR не направлен на создание контента, только перенос доки и починку всего. Поэтому в следующих PR.

2024-06-23 18:07 UTC, shadowusr commented on docs/commands/browser/action.mdx
> +    await browser.action("key").down("f").down("o").down("o").up("f").up("o").up("o").perform();
Добавил коммент об этом.

2024-06-23 18:12 UTC, shadowusr commented on docs/commands/browser/action.mdx
> +-   `down(value: string)` &mdash; создает действие нажатия клавиши;
Заменил mdash на `—`. Надо бы уточнить у rashid, зачем он делал именно так, думаю не без причины.

2024-06-23 21:46 UTC, merged